### ISSUE TITLE
Unstable Import Paths

### ISSUE THREAD

**Issue by markbates** [gofrs/uuid#61] opened 2018-11-19 15:13 UTC
With the introduction of the `go.mod` file and declaration of `github.com/gofrs/uuid/v3` there is no longer a single import path that works correctly for both modules and non-modules users.

This has become an issue with gobuffalo/pop and other Buffalo projects.

Below you find a selection of `go get` statements that represent the different import paths and what happens when trying to use them in different environments.

### Go >1.9.7 (or `GO111MODULE=off`)

```bash
$ go get github.com/gofrs/uuid/v3

package github.com/gofrs/uuid/v3: cannot find package "github.com/gofrs/uuid/v3" in any of:
    /usr/local/go/src/github.com/gofrs/uuid/v3 (from $GOROOT)
    /go/src/github.com/gofrs/uuid/v3 (from $GOPATH)
```

### Go 1.11 (`GO111MODULE=on`)

```bash
$ go get github.com/gofrs/uuid
```

```go.mod
module github.com/gobuffalo/uuidmods

require github.com/gofrs/uuid v3.1.0+incompatible // indirect
```

```bash
$ go get github.com/gofrs/uuid/v3
```

```go.mod
module github.com/gobuffalo/uuidmods

require (
	github.com/gofrs/uuid/v3 v3.1.2 // indirect
)
```

**Comment by adamdecaf** [comment] 2018-11-19 17:57
Isn't `github.com/gofrs/uuid/v3 v3.1.2 // indirect` the desired outcome? I'm not aware of any cross Go version support for Go module import paths.

**Comment by markbates** [comment] 2018-11-19 18:00
It is, but notice that go modules only resolves to 3.1.0 with gofrs/uuid when using mods.

So, yes, when using modules and /v3 everything works correctly. But if you use that, then it breaks those not use modules.

If you don’t use /v3 it works for both, but won’t resolve past 3.1.0.

**Comment by adamdecaf** [comment] 2018-11-19 18:04
> So, yes, when using modules and /v3 everything works correctly. But if you use that, then it breaks those not use modules.

Yea and I'm not sure of support for compiling Go <1.11 with module import paths. This sounds like a problem all Go projects that adopt modules and cross compile have.

**Comment by markbates** [comment] 2018-11-19 18:16
There are two ways you can fix it.

* Create a branch called `/v3` and use that from now on
* Create a folder called `/v3` and use that from now on. (this is the approach I'm taking with https://github.com/gobuffalo/packr/tree/master/v2)

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by markbates** [comment] 2018-11-19 19:00
I believe the branch approach only works for >1.9.7, but don't quote me on that.

**Comment by bcmills** [comment] 2018-11-19 20:21
See https://github.com/golang/go/issues/27430 and https://github.com/golang/go/issues/25967#issuecomment-422828770.

For maximum compatibility, leave the original `v3` package at its existing import path (with the `+incompatible` version suffix and no `go.mod` file), and start a new major version (`/v4`) in a subdirectory. That will be unambiguous for all importers, including those on pre-1.9.7 toolchains.

**Comment by thepudds** [comment] 2018-11-20 03:02
Hi all,

I wanted to circle back to the original problem report for this issue:

> With the introduction of the go.mod file and declaration of github.com/gofrs/uuid/v3 there is no longer a single import path that works correctly for both modules and non-modules users.
> 
> ...
> 
> Below you find a selection of go get statements that represent the different import paths and what happens when trying to use them in different environments.
> 
> ### Go >1.9.7 (or GO111MODULE=off)
> $ go get github.com/gofrs/uuid/v3
> 
> package github.com/gofrs/uuid/v3: cannot find package "github.com/gofrs/uuid/v3" in any of:
>     /usr/local/go/src/github.com/gofrs/uuid/v3 (from $GOROOT)
>     /go/src/github.com/gofrs/uuid/v3 (from $GOPATH)

and:

> when using modules and /v3 everything works correctly. But if you use that, then it breaks those not use modules.

The bit I wanted to try to clarify is that IF you are using Go 1.9.7 as a client of this `uuid` package, then things do work and you can avoid that error shown in the original problem report.

Part of the tricky bit is that if you are using Go 1.9.7, then I believe you should *not* include the `/v3` in the 'go get' command. Using the `/v3` in the 'go get' command is what I think is triggering the error in the original report.

It might be simplest to show by example. Here we'll download an older Go 1.9.7 toolset, then show getting, importing, and using `github.com/gofrs/uuid` in a trivial client:

```
# 1. Verify we do *not* have GO111MODULE set:

$ echo $GO111MODULE

# 2. Install Go 1.9.7 if we don't have it:

$ go get golang.org/dl/go1.9.7
$ go1.9.7 download

# 3. Using Go 1.9.7, 'go get' the package of interest.
# KEY POINT: do not use '/v3' for 'go get' here:

$ go1.9.7 get github.com/gofrs/uuid

# 4. Still using Go 1.9.7, we create, build, and run a trivial client within GOPATH:

$ mkdir -p $GOPATH/src/example.com/sratchpad/uuidhello
$ cd $GOPATH/src/example.com/sratchpad/uuidhello
$ cat <<EOF > hello.go
package main

import (
	"fmt"
	"github.com/gofrs/uuid"
)

func main() { fmt.Println(uuid.Must(uuid.NewV4())) }

EOF

# 5. Build using Go 1.9.7, then run successfully:

$ go1.9.7 build .
$ ./uuidhello

e3ef4eea-6df5-420e-a6b7-39e3b2be0927
```

That behavior demonstrated there is part of the "minimal module awareness" that was added to Go versions 1.9.7+, 1.10.3+ and non-module-mode 1.11 so that code built with those releases can properly consume v2+ modules without requiring modification of pre-existing code. That behavior is covered in a little more detail here:

* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://go-review.googlesource.com/c/go/+/109340

And as @markbates already demonstrated above in https://github.com/gofrs/uuid/issues/61#issue-382259495, code that has opted in to modules using Go 1.11 ends up working as well.

The net of all that is that IF you are willing to require clients to use versions Go 1.9.7+, 1.10.3+, and 1.11, then I think things work.

However, if you want to support versions older than Go 1.9.7, then the `/v3` subdirectory approach mentioned by @markbates and @bcmills (https://github.com/gofrs/uuid/issues/61#issuecomment-440028945) is an avenue to support even older versions of Go.

All that said, I am not sure what is the best alternative to support the particular goals of this project. I am just a member of the community trying to share my personal understanding of how things currently work, but I am certainly happy to learn more, and apologies in advance if anything I've said here is off-base.

**Comment by markbates** [comment] 2018-11-20 03:30
This has NOTHING To do with old versions. It’s about an import path that works for ALL versions.

Can we just add the sub folder and close this issue? It’s easy to fix as Bryan has pointed out.

It’s silly to continue this discussion when we could finish it.

**Comment by acln0** [comment] 2018-11-20 03:31
Thanks for the detailed report. I think we should do everything we can to support all users, and as many Go versions as we can. It is still not clear to me exactly what we should do, though.

@markbates says we should use a `v3` subdirectory.

On the other hand, @bcmills says we should use a `v4` subdirectory and leave the original `v3` package at its current import path with no `go.mod`. But we do have a `go.mod` for `v3`, at `v3.1.1`. Is that one not good? Should we remove it?

In any case, it seems like moving one version of the package into a `vX` subdirectory is the way forward. In this case, where do we put the `go.mod`? I noticed in @markbates packr repository that both the root directory and the `v2` subdirectory have their own `go.mod`.

**Comment by markbates** [comment] 2018-11-20 03:38
I'm with fine with either `/v3` or `/v4` sub directory. I would tend to agree with @bcmills as it's best to just put the whole thing in the past to move it forward.

Packr is `1.x` in the root and `2.x` in `/v2`. From what I believe, and the docs aren't clear on it, is whether you need one in each directory or not. I err'd on the side of "go modules do weird things right now and better safe than sorry".

**Comment by acln0** [comment] 2018-11-20 03:39
Hmm, looking at it more, it seems like should have bumped major versions when adding modules support, but we didn't. Is that the cause of `go get github.com/gofrs/uuid` resolving to `require github.com/gofrs/uuid v3.1.0+incompatible` when using modules and not explicitly specifying `/v3`?

Given that we, unfortunately, didn't bump major versions, what is the best course of action now? Should we rectify the mistake by moving to `v4`?

**Comment by markbates** [comment] 2018-11-20 03:41
Yeah, the "logic" is to use that last version that *didn't* have a `go.mod` if you don't use `/v3` but *are* using modules. That's the underlying issue with this this bug.

My vote, is `/v4`, and y'all should write a blog post to demonstrate this issue. :)

**Comment by acln0** [comment] 2018-11-20 03:49
Okay. Sorry if I'm being obtuse, but I want to make sure we get everything right, so I will recap. My understanding is that for maximum compatibility, we should:

* leave the current contents of the root directory untouched
* create a copy of the code in a `/v4` subdirectory
* create a `go.mod` with `module github.com/gofrs/uuid/v4` in the `/v4` subdirectory
* update the documentation to recommend `github.com/gofrs/uuid/v4` as the one true import path that works for everyone
* push all of this up, then cut v4.0.0

Does that sound right?

**Comment by markbates** [comment] 2018-11-20 04:01
You should remove the root go.mod as well, since root is actually v3.

**Comment by bcmills** [comment] 2018-11-20 13:48
I agree with @markbates: if existing call sites are written against `v3.x.x` with the non-`/v3` import path, to get them to build in module mode you'll want a `v3.x.x+incompatible` version, which implies removing the `go.mod` file and tagging the result (probably as `v3.1.3`).

(The presence of the `go.mod` file signals that you're using semantic import paths.)

**Comment by bcmills** [comment] 2018-11-20 14:01
@acln0:
> create a copy of the code in a `/v4` subdirectory

Note that `/v4` doesn't have to be a _copy_. It can forward functions and types back to the non-`/v4` path, or you can **move** (not copy) the code to `/v4` and rewrite the non-`/v4` path to forward to `/v4`. That would reduce the maintenance overhead, since bug-fixes in one path would automatically apply to the other as well. (That's what the `goforward` tool is for.)

**Comment by thepudds** [comment] 2018-11-20 18:46
Two related but perhaps separable questions might be:

Q1. What does the gofrs organization view as the best path forward for the `gofrs/uuid` package regarding modules?

Q2. Is the `gofrs/uuid` repo broken as it stands today?

There is a discussion going on elsewhere within the gofrs team regarding Q1, I think.

One semi-related question: does anyone know the minimum version of Go required for `gobuffalo/pop` currently? The `gobuffalo` documentation seems to suggest Go 1.9.7+ is required:

https://gobuffalo.io/en/docs/installation#requirements
> Before installing make sure you have the required dependencies installed:
> ...
> Go version 1.9.7 or greater.

But I am not a `gobuffalo` user, so not sure if that is the right place to look.

**Comment by thepudds** [comment] 2018-11-20 19:51
Regarding:

> Q2. Is the gofrs/uuid repo broken as it stands today?

Having looked at it a bit more, as far as I can tell:
* It seems the `gofrs/uuid` repo in effect currently requires Go 1.9.7+, 1.10.3+ or 1.11. 
* The `gofrs/uuid` repo in its current state seems to work with those versions of Go.
* However, it might not have been intentional that `gofrs/uuid` in effect requires Go 1.9.7+, 1.10.3+ or 1.11.

Of course, happy to learn more here, and this is not based off of any type of exhausting testing or assessment.

**Comment by stanislas-m** [comment] 2018-11-20 19:54
> One semi-related question: does anyone know the minimum version of Go required for gobuffalo/pop currently?

Go 1.9.7+, the same requirements as gobuffalo/buffalo.

**Comment by markbates** [comment] 2018-11-20 19:54
Once again, YES IT IS BROKEN if you care about supporting everyone with the same import path. Please stop arguing that point, everyone else agrees it is broken.

-----------
Mark Bates

**Comment by bcmills** [comment] 2018-11-20 20:07
@markbates, we're all trying to figure out a useful path forward. Please [be patient and charitable](https://golang.org/conduct#values).

You say:
> This has become an issue with gobuffalo/pop and other Buffalo projects.

But you haven't said what the concrete issue is. If `gofrs/uuid` already requires Go 1.9.7+, then all existing code that does not have a `go.mod` file can use the non-`/v3` import path, and all existing code that does have a `go.mod` file can use the `/v3` import path (in both module mode and `GOPATH` mode).

Is the problem:
* that users of `gobuffalo/pop` are using Go versions that predate 1.9.7?
* that users are confused as to how to enable the `/v3` import path?
* something else?

**Comment by markbates** [comment] 2018-11-20 20:18
@bcmills I apologize for getting upset, but I have dealt with this issue on several repos now, and it gets wearisome having the same conversation with the same people.

The problem is that if you import `gofrs/uuid` using go modules it stops at `3.1.0` because it is not compatible with semantic import paths and uses the last known version without a mod, which is `3.1.0` not `3.1.2`. This import path works correctly for those not using modules.

To support module users you need to `gofrs/uuid/v3` which breaks non-module users.

All I want is ONE path I can use to support everyone.

Right now I'm forced to choose whether I want to support non-module users with `gofrs/uuid` and tell module users "sorry you're not going to get any updates because of this" or use `gofrs/uuid/v3` and tell all of our non-module users to go bye-bye.

It's terrible decision to have to make, when the answer is to simple implement semantic import versioning correctly in the repo.

My hands are shaking so much from this thread, that I am now officially removing myself from the discussion. 

I don't want to force any project to support people they want.

**Comment by DamareYoh** [comment] 2018-11-20 22:30
How likely are we to hate the v4 directory in the future, and what's the potential to revert to a different practice?

**Comment by bcmills** [comment] 2018-11-20 22:47
If you're assuming Go 1.9.7 and up, you shouldn't even need a `/v4` directory. If you want to follow the “major branch” layout instead, you can switch to a `v4.x.y` tag and leave everything in the directory where it is today: it's the `v3.1.3` forwarding shim that does the heavy lifting, and that only has to be in place for a single commit (which doesn't even have to be on the `master` branch).

**Comment by thepudds** [comment] 2018-11-20 23:13
@stanislas-m Based on your comments, I am operating under the assumption that you are OK with Go 1.9.7+.

The gofrs organization might be shortly pick a different path forward here, but _right now_, as far as I can tell, the `gofrs/uuid` repo in effect currently requires Go 1.9.7+, 1.10.3+ or 1.11, and "things work" (if you are using those versions of Go, which seems to be your personal case, if I followed).

I wanted to show three quick examples of how "things work", where these examples are based off of your example.

**PREP**: start with clean slate.
```bash
rm -rf $GOPATH/src/github.com/gofrs/uuid/
rm -rf $GOPATH/src/example.com/scratchpad/ 
```

**SCENARIO 1**: 
* @stanislas-m first example, which is a non-module based consumer.
* go 1.11.1, modules disabled and no go.mod file
* BUT, we correct his import path to NOT use `uuid/v3` because this code has not opted in to modules, and code that has not opted in to modules should not use `/v3` in the import path when importing a v3 module.

```bash
mkdir -p $GOPATH/src/example.com/scratchpad/nomodconsumer
cd $GOPATH/src/example.com/scratchpad/nomodconsumer

# Verify we do *not* have GO111MODULE set:
echo $GO111MODULE

# Create our code:
cat <<EOF > nomodconsumer.go
package main

import (
        "fmt"
        "github.com/gofrs/uuid"
)

func main() {
        id, err := uuid.NewV4()
        if err != nil {
                panic(err)
        }
        fmt.Println(id)
}

EOF

# 'go get'. Note that we do a normal 'go get' here without `/v3'
go get github.com/gofrs/uuid

# build, which succeeds:
go build .

# run:
./nomodconsumer
4b8d47d9-db8f-4f07-8b1c-9a594da15e3f
```

**SCENARIO 2**:
* a module-based consumer library
* the import path DOES use `uuid/v3` because this code HAS opted in to modules.

```bash
mkdir -p $GOPATH/src/example.com/scratchpad/modconsumer
cd $GOPATH/src/example.com/scratchpad/modconsumer

# Init our module:
GO111MODULE=on go mod init example.com/scratchpad/modconsumer

# Create our code:
cat <<EOF > modconsumer.go
package modconsumer

import (
        "github.com/gofrs/uuid/v3"
)

func ModConsumer() uuid.UUID {
        id, _ := uuid.NewV4()
        return id
}

EOF

# build, which is successfull
GO111MODULE=on go build .

# review the resulting go.mod
cat go.mod

module example.com/scratchpad/modconsumer

require github.com/gofrs/uuid/v3 v3.1.2
```

**SCENARIO 3**:
* mixed mode: this effectively mixes both of our prior scenarios together in a single build - a non-module main, with a module-based lib.
* **Key point**: it might seem surprising, but we are mixing the `/v3` and no-`/v3` import paths in a single build.
* The main package does NOT use `uuid/v3` because this code has not opted in to modules, and code that has not opted in to modules should not use `/v3` in the import path when importing a v3 module.
* The lib is the exact lib from Scenario 2 (which DOES use `uuid/v3` when importing because the lib HAS opted in to modules).

```bash
mkdir -p $GOPATH/src/example.com/scratchpad/mixedconsumer
cd $GOPATH/src/example.com/scratchpad/mixedconsumer

# Verify we do *not* have GO111MODULE set:
echo $GO111MODULE

cat <<EOF > mixedconsumer.go
package main

import (
        "fmt"
        "github.com/gofrs/uuid"
        "example.com/scratchpad/modconsumer"
)

func main() {
        id1, _ := uuid.NewV4()
        id2 := modconsumer.ModConsumer()
        fmt.Println(id1)
        fmt.Println(id2)
}

EOF

# 'go get'. Note that we do a normal 'go get' here without `/v3'
go get github.com/gofrs/uuid

# build, which succeeds:
go build .

# run:
./mixedconsumer
7eb7f462-9ed5-40b1-92c2-3c88b6a9e20b
8fff234f-f563-48e0-8ff9-24dccf336858
```

### SUMMARY

* Things work.
* As @bcmills said: 
> existing code that does not have a go.mod file can use the non-/v3 import path, and all existing code that does have a go.mod file can use the /v3 import path (in both module mode and GOPATH mode).
* The examples here are entirely about the current state of this repo. 
* There is an entirely different set of questions for the gofrs organization about how they want to proceed moving forward.

**Comment by bcmills** [comment] 2018-11-21 12:52
Hmm, come to think of it, you might not even need to switch to major version 4. You could make `v3.2.0` a forwarding package (without a `go.mod`) to `github.com/gofrs/uuid/v3`), with a corresponding `v3.3.0` (with a `go.mod`) that provides the `/v3` module.

**Comment by itsjamie** [comment] 2018-11-21 14:01
@bcmills: do you happen to know the reason for the two different resolutions of commits for a user running `gofrs/uuid` path and a user who imports `gofrs/uuid/v3`. Why is the user who hasn't opted into running the modules import path penalized by the automatic resolution code if the library does have a `go.mod` file.

I believe this behaviour is the crux of the issue in this case.

**Comment by stanislas-m** [comment] 2018-11-21 14:12
I got another case, with an existing `Gopkg.toml` from dep:

```toml
[[constraint]]
  name = "github.com/gofrs/uuid"
  branch = "master"
```

(same behavior with a version constraint)

The version found by go modules:

```
github.com/gofrs/uuid v0.0.0-20181030014311-7077aa611296
```

Then, `go run .`:
```bash
$ go run .
go: github.com/gofrs/uuid@v0.0.0-20181030014311-7077aa611296: go.mod has post-v0 module path "github.com/gofrs/uuid/v3" at revision 7077aa611296
go: error loading module requirements
```

**Comment by stanislas-m** [comment] 2018-11-21 14:41
> Is that part of the require statements in the resulting go.mod?

Yes.

It got rewritten by the `go build` to:

```
github.com/gofrs/uuid v3.1.0+incompatible
github.com/gofrs/uuid/v3 v3.1.2
```

This one seems to compile, even if it's not straightforward.

**Comment by thepudds** [comment] 2018-11-21 14:53
@stanislas-m 

Good, that is hopefully progress.

I think the way that it works is `go mod init` focuses on converting things like commit hashes or VCS tags from `dep` (in your case) into terminology understood by `go.mod`, but I think `go mod init` does _not_ modify your `.go` code itself to change your code to use semantic import versioning, at least as far as I am aware. (And that is probably a good thing).

So if you just now had run `go mod init` inside some package, you probably should also check the import statements in the `.go` code in that package, and where needed, try editing the code to add the `/v3` to any `import "github.com/gofrs/uuid"` so that it reads `import "github.com/gofrs/uuid/v3"`, and try building again.

There is some tooling to automate this code edit, I think, but might be best to start with manual inspecting/manual edit.

**Comment by stanislas-m** [comment] 2018-11-21 15:00
> try editing the code to add the /v3 to any import "github.com/gofrs/uuid" so that it reads import "github.com/gofrs/uuid/v3", and try building again.

I can't do that in this project (and some others). I'm only **testing** go modules to convert an enterprise project, **so go modules have to live beside the dep tooling**. In other terms, it have to work with both dep and go modules, and with the same versions. I can alter the current code if it still works with the dep version, though.

**Comment by acln0** [comment] 2018-11-21 16:00
> Hmm, come to think of it, you might not even need to switch to major version 4. You could make `v3.2.0` a forwarding package (without a `go.mod`) to `github.com/gofrs/uuid/v3`), with a corresponding `v3.3.0` (with a `go.mod`) that provides the `/v3` module.

I want to understand this better, so I'm going to try to spell it out.

At v3.2.0, there would be no `go.mod` in the root, we would have a `v3` subdirectory containing all the code, and forwarding declarations from `github.com/gofrs/uuid` to `github.com/gofrs/uuid/v3`. This means that at v3.2.0, all clients could consume `github.com/gofrs/uuid` as well as `github.com/gofrs/uuid/v3` (modulo `+incompatible` for modules users). At v3.3.0, the `v3` subdirectory would be removed and `github.com/gofrs/uuid` would provide a `go.mod` with `module github.com/gofrs/uuid/v3`.

Is that right?

**Comment by itsjamie** [comment] 2018-11-21 16:04
# Current Issues

### *Buffalo users can't build.*

@markbates I believe that you should get the behaviour you want if you upgrade all of your code that is module-aware to use the `gofrs/uuid/v3` path.

This will limit correct behaviour to these versions of Go that are "minimal module aware" (Go 1.9.7+, 1.10.3+, 1.11) until we address part 2, but is a good stop-gap. However I believe that works for your user-group in the immediate based on your need so long as they don't explicitly disable modules when building.

----

#### *gofrs/uuid cannot be used by a module aware library for < 1.9.7 || < 1.10.3 || < 1.11 that wants to support non-module users*

@gofrs/leadership if we want to support less than those versions in an open environment where other libraries import us which use modules, and then non-module users use them, we need to create a v3 subdirectory as discussed above and alias our API there. I believe that we should since it's a relative small lift, especially with automation going forward.

@bcmills has a tool that will help with that going forward (heh) `goforward`.

**Comment by stanislas-m** [comment] 2018-11-21 16:06
> Mixed mode: this effectively mixes both of our prior scenarios together in a single build - a non-module main, with a module-based lib.

@thepudds With pop, this is the other way. Pop is a non-module lib right now, and I don't expect it to migrate to go modules in the few weeks.

I haven't tested your examples yet, I'm still at work.

**Comment by bcmills** [comment] 2018-11-26 17:22
> I want to understand this better, so I'm going to try to spell it out.
> 
> At v3.2.0, there would be no `go.mod` in the root, we would have a v3 subdirectory containing all the code, and forwarding declarations from `github.com/gofrs/uuid` to `github.com/gofrs/uuid/v3`.

You don't strictly need the `v3` subdirectory: you can just have a `v3.2.0` with no `go.mod`.

If you do have the subdirectory, you can do the whole thing in one commit and one tag (instead of two commits and two tags).

The two options are as follows:

----

Following the **major subdirectory** model (see https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher):

```
v3.2.0
forward.go:
	package uuid // import "github.com/gofrs/uuid"
	import "github.com/gofrs/uuid/v3"
	[…]
v3/go.mod:
	module "github.com/gofrs/uuid/v3"
	[…]
v3/codec.go:
	package uuid // import "github.com/gofrs/uuid/v3"
	[…]
v3/[…]
```

The two corresponding `require` statements for importers are then:
```
require (
	github.com/gofrs/uuid    v3.2.0+incompatible // for the non-v3 import path
	github.com/gofrs/uuid/v3 v3.2.0              // for the v3 import path
)
```

At that point you would effectively have two modules in the repository: one at the original import path (without a `go.mod`), and one at the new path. Users could update those two modules independently, but the non-`v3` path would always forward to whatever version of the `/v3` module is actually active.
(The `v3.2.0+incompatible` version sets the version of the forwarding package, not the version it forwards to.)

----

Following the **major branch** model, the `require` statements would need to split.

```
v3.2.0
forward.go:
	package uuid // import "github.com/gofrs/uuid"
	import "github.com/gofrs/uuid/v3"
	[…]
```

```
v3.3.0
go.mod:
	module github.com/gofrs/uuid/v3
	[…]
codec.go
	package uuid // import "github.com/gofrs/uuid/v3"
	[…]
[…]
```

```
require (
	github.com/gofrs/uuid    v3.2.0+incompatible // for the non-v3 import path
	github.com/gofrs/uuid/v3 v3.3.0              // for the v3 import path
)
```

The user's view of the modules would be similar, except that they would see `v3.2.0+incompatible` as the last available version of the non-`v3` path. (It would still forward to whichever version of the `/v3` module is active.) Any future additions to the package API would either only appear on the `/v3` path, or would need to be backported to the `v3.2.x` line as patch releases.

----

In both cases, note that adding another declaration to the forwarding package (without a `go.mod` file) is a breaking change: the forwarding package requires a version of `/v3` that supplies a complete implementation, and without a `go.mod` file it has no way to declare that version.

(You could play some games with blank-imports and dummy modules to synthesize the right requirement graph for additions, but that seems excessive: if someone is updating their code to make use of a new part of the API, they may as well update the import path to `/v3` in the process.)

**Comment by acln0** [comment] 2018-11-26 18:01
@bcmills Thanks.

Using the major subdirectory model, would it be possible to do it the other way around? To have the contents of `/v3` be forwarding declarations to the root package?

I dislike how if `github.com/gofrs/uuid` forwards everything to `/v3`, the godoc for `uuid` is incomplete, since it consists of forwarding declarations only. Meanwhile, the godoc for `uuid/v3` is complete, but contains the unpleasant name mismatch between `v3` and `uuid`.

**Comment by bcmills** [comment] 2018-11-26 18:44
> Using the major subdirectory model, would it be possible to do it the other way around? To have the contents of `/v3` be forwarding declarations to the root package?

The forwarding itself should work fine, but if you're doing active development in a part of the tree that lacks a `go.mod` file, you'll need to periodically bump the requirements in the `/v3` module to pick up the changes. (Probably every time you push a new tag to the `+incompatible` path you'll want to add that same tag — and the corresponding `require` directive — to the `v3/go.mod` file.)

> I dislike how if `github.com/gofrs/uuid` forwards everything to `/v3`, the godoc for `uuid` is incomplete, since it consists of forwarding declarations only.

The approach I'm taking with `goforward` is to explicitly duplicate the documentation comments in the forwarding package. (That feature accounts for a significant fraction of the complexity of the tool.) The duplication is a bit unfortunate, but (absent adding `godoc` logic to somehow propagate comments automatically) it seems preferable to dropping the documentation from one package or the other.

> Meanwhile, the godoc for `uuid/v3` is complete, but contains the unpleasant name mismatch between `v3` and `uuid`.

Package paths that end in `/vN` will likely be much more common going forward, so I expect that Go users in general will learn to read `uuid/v3` as “`uuid`” rather than “`v3`”.

**Comment by thepudds** [comment] 2018-11-26 19:12
@stanislas-m

> @thepudds With pop, this is the other way. Pop is a non-module lib right now, and I don't expect it to migrate to go modules in the few weeks.

In case it helps, over the weekend I put together two more small runnable examples using the current state of the `uuid` repo, including flipping around the "mixed mode" example in Scenario 3 in from my prior examples in https://github.com/gofrs/uuid/issues/61#issuecomment-440462822 .

You can see the new examples here in [this gist](https://gist.github.com/thepudds/9e0802c99774c0ad5075000e0a04cf59), if interested.
    
Scenario 5 in that gist I think is a simple scenario that is closer to what you were suggesting as an additional example in your comment above. For Scenario 5:
* It is "mixed mode"
* It has a module-based main package that imports `uuid`
* The main package imports a non-module library that also imports `uuid`
* The top-level build enables modules via GO111MODULE=on
* It builds successfully
* The versions of `uuid` included in this mixed build are:
  * `github.com/gofrs/uuid v3.1.0+incompatible`
  * `github.com/gofrs/uuid/v3 v3.1.2`
* Given the import paths are different, the `uuid` types are different, e.g.:
  * `"github.com/gofrs/uuid/v3".UUID` vs.
  * `"github.com/gofrs/uuid".UUID`

**Comment by theckman** [comment] 2018-12-03 16:46
Sorry for the delay in reading this; been a busy few weeks including a last-minute trip to Vegas for re:Invent. 😪

So it sounds like we need to remove the `go.mod` file from the `3.x` line, mark those releases as unstable, put some messaging up on the README about intentionally breaking the `github.com/gofrs/uuid/v3` import path and that we have no intent on explicitly supporting modules until the Go authors have a better story? Then later decide whether we want to cut a v4.0.0 tag with the `go.mod` file?

**Comment by acln0** [comment] 2018-12-03 16:48
What about the forwarding declarations? Did you catch that part of the proposed solution? Have you looked at https://github.com/gofrs/uuid/commit/c6f696b8aab1385872bdb55a01e019d46574e9b8? Is this not acceptable either? Are we breaking current /v3 callers altogether?

**Comment by theckman** [comment] 2018-12-03 16:49
@markbates Please don't apologize for being frustrated; it's on the Go authors for pushing modules on to us. I'm getting more and more frustrated trying to defend the choices to outsides / newcomers to Go, especially when I don't believe in it myself.

**Comment by theckman** [comment] 2018-12-03 16:49
@acln0 I think the streams may have been crossed with my edit:

>**Edit:** To be clear, I firmly believe in Rob Pike's "A little copying is better than a little dependency", but creating a separate directory for different code versions isn't acceptable to me.

**Comment by acln0** [comment] 2018-12-03 16:59
You are proposing to intentionally break the builds of callers who are using the `/v3` import path. Under any other circumstances, I don't think you would have agreed to a change that breaks someone's build intentionally. But in this particular case, you are letting your personal opinions about modules guide your reasoning on this matter, and you are going in a direction that I do not want to be a part of.

We made a mistake introducing the go.mod file as we did, and now we need to own up to that mistake, not break people's builds because of our personal opinions.

**Comment by theckman** [comment] 2018-12-03 17:04
@acln0 Everyone here has commit access and can pursue anything they want. I am not a decider, gate-keeper, or benevolent dictator. I am offering my opinion of what I don't wish to support or pursue, if others in the Gofrs wish to purse that I am not a blocking voice.

And to that point, since it seems my dislike of modules has become so contentious to the Gofrs organization and my intent when starting the group, I hereby relieve myself of technical involvement in deciding in this issue and others.

**Comment by theckman** [comment] 2018-12-03 17:04
In other words, move forward how y'all feel appropriate on this issue. Let me know what I can do to support that decision.

**Comment by theckman** [comment] 2018-12-03 18:30
It's worth doing some homework on this to understand what exactly we're going to break and how. We should test with multiple toolchain versions, `dep`, `glide`, and with modules support.

We're also going to provide a detailed experience report to the Go authors if any interesting findings come out of it.

**Closed** 2019-01-11 07:19 UTC

**Comment by theckman** [comment] 2019-01-11 17:35
@DamareYoh Thank you for adding the summary here. In the interest of full transparency because there's a lot of context in this issue: as `modules` becomes mature, and other things happen in the ecosystem to better support interoperability, we will adopt modules so that we are able to meet the needs of the community.

**Comment by markbates** [comment] 2019-01-11 17:54
Removing modules in v3 was what I was hoping for, so I’m happy. I would love to see a /v4 that did have modules though. :)
